// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC6VCM5vySENwgJLvEiLUtkH-X8SQTmZU',
    appId: '1:727269920144:web:ebc8dc9d70b35f1c727715',
    messagingSenderId: '727269920144',
    projectId: 'perfectship-app',
    authDomain: 'perfectship-app.firebaseapp.com',
    storageBucket: 'perfectship-app.appspot.com',
    measurementId: 'G-PKRDYX39GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6ePFbr5urf5paqGAB8XheGuE8OOXuDy8',
    appId: '1:727269920144:android:c9c50968498deed5727715',
    messagingSenderId: '727269920144',
    projectId: 'perfectship-app',
    storageBucket: 'perfectship-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBec17Omnfd7uV1q8ZcNf6ktl-ufY9zJLs',
    appId: '1:727269920144:ios:9dd178245128b1d0727715',
    messagingSenderId: '727269920144',
    projectId: 'perfectship-app',
    storageBucket: 'perfectship-app.appspot.com',
    androidClientId: '727269920144-8hjcf4ijra9b07rg96c6qmi2hpccco7p.apps.googleusercontent.com',
    iosClientId: '727269920144-93or8fp257g95s4op2se3du9af36b1o9.apps.googleusercontent.com',
    iosBundleId: 'com.perfectship.app',
  );
}
